pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('report/', include(('report.urls', 'report'), namespace='report')),
    path('transaction/', include(('transaction.urls',
                                  'transaction'), namespace='transaction')),
]

report/urls.py
from django.urls import path
import report.views as views

urlpatterns = [
    path('', views.index, name='index'),
]

transaction/urls.py
from django.urls import path
import transaction.views as views

urlpatterns = [
    path('', views.index, name='index'),
]

report/models.py
from django.db import models

# Create your models here.

transaction/models.py
from django.db import models


class Transaction(models.Model):
    product_code = models.CharField(max_length=200, null=False)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0)

    def __str__(self):
        return self.product_code+'_'+str(self.quantity)+'_'+str(self.price)
        #return self.product_code+'_'+str(self.quantity)+str(self.price)

transaction/forms.py
from django import forms
from .models import Transaction


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'

report/views.py
from django.shortcuts import render
from transaction.models import Transaction


def index(request):
    transactions = Transaction.objects.all()
    return render(request, 'report/index.html', {'transactions': transactions})

transaction/views.py
from django.shortcuts import render, redirect
from .models import Transaction
from .forms import TransactionForm


def index(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = TransactionForm()
    return render(request, 'transaction/index.html', {'form': form})

report/templates/report/index.html
<html>

<head>
    <title>POS Report</title>
</head>

<body>
    {% if transactions.count == 0 %}
    <p>No transactions yet.</p>
    {% else %}
    <ul>
        {% for t in transactions %}
        <li>{{t}}</li>
        {% endfor %}
    </ul>
    {% endif %}
</body>

</html>

transaction/templates/transaction/index.html
<html>

<head>
    <title>POS</title>
</head>

<body>

    <form action="{% url 'transaction:index' %}" method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" id="submit" value="Submit">
    </form>
    <a id="link" href="/report">Show report</a>
</body>

</html>